### ISSUE TITLE
while running triangulation.py in ps2 shows me the following error..please help me how to resolve this!!

### ISSUE THREAD

**Issue by Dhanalakshmi07** [zyxrrr/cs231a#2]
Traceback (most recent call last):
  File "/home/dhana/.virtualenvs/cv/lib/python3.5/site-packages/numpy/lib/format.py", line 647, in read_array
    array = pickle.load(fp, **pickle_kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 4: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "triangulation.py", line 283, in <module>
    'matches_subset.npy'))[0,:]
  File "/home/dhana/.virtualenvs/cv/lib/python3.5/site-packages/numpy/lib/npyio.py", line 421, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/dhana/.virtualenvs/cv/lib/python3.5/site-packages/numpy/lib/format.py", line 653, in read_array
    "to numpy.load" % (err,))
UnicodeError: Unpickling a python object failed: UnicodeDecodeError('ascii', b'\x00\x00\x00\x00\xc8#Z@\x00\x00\x00\xc0\x856e\xc0\x00\x00\x00\x00\xfc\x92^@\x00\x00\x00\x00BAc\xc0\x00\x00\x00@3\x06W@\x00\x00\x00\x80\x1f_j\xc0\x00\x00\x00 \x99\xb6^@\x00\x00\x00\x80\xceuh\xc0\x00\x00\x00\x00:YC@\x00\x00\x00\x00\x8e\xc6j\xc0\x00\x00\x00@\x0cIS@\x00\x00\x00\x00\x93\xddi\xc0\x00\x00\x00\x00\xe1\x9b<@\x00\x00\x00\x80\xb7yZ\xc0\x00\x00\x00\x80\xc1TI@\x00\x00\x00\x00\x82~Y\xc0\x00\x00\x00\x00\x88\xb38\xc0\x00\x00\x00\xc0\x19\x9fU@\x00\x00\x00\x00\xb8K*@\x00\x00\x00\xc0A:U@\x00\x00\x00\x00?\x1f@\xc0\x00\x00\x00\x00\xfb*n\xc0\x00\x00\x00\x00!\x885@\x00\x00\x00\x80\xc6\xb4n\xc0\x00\x00\x00\x00e\x80@\xc0\x00\x00\x00@0\xc1e@\x00\x00\x00\x00\xd4\xe9!@\x00\x00\x00\x00\r\xc0e@\x00\x00\x00\x00\x06\xb8A\xc0\x00\x00\x00\x00\xcb\x1df\xc0\x00\x00\x00\x00\xf4u\x14\xc0\x00\x00\x00\xc0S\xb1f\xc0\x00\x00\x00\x00\xbc\x02D\xc0\x00\x00\x00\x00{>i\xc0\x00\x00\x00\x00@U\xde?\x00\x00\x00\x00f\xf9i\xc0\x00\x00\x00\x00u\x03\\\xc0\x00\x00\x00\x80{W\\\xc0\x00\x00\x00\x00\x88%[\xc0\x00\x00\x00\x00\xf1\r`\xc0\x00\x00\x00(\x83\xd3g@\x00\x00\x00~!\x89r@\x00\x00\x00\x80Y\xfcD@\x00\x00\x00I\xf0;s@\x00\x00\x00\x80v\'S@\x00\x00\x00\xc0\x0b\x9bj@\x00\x00\x00\x00\x87dZ@\x00\x00\x00\xf0Y?k@\x00\x00\x00\xc0\xf2\x1cR@\x00\x00\x00\x80,\xd4`@\x00\x00\x00\xc0\x98\xe4\\@\x00\x00\x00\xa0\x83\x8da@\x00\x00\x00\x00x\x88;@\x00\x00\x00\x00\xce}Q\xc0\x00\x00\x00\x00KZI@\x00\x00\x00\x00y\xbaP\xc0\x00\x00\x00\x00\xd1\x117@\x00\x00\x00\x80\x079h\xc0\x00\x00\x00\x80/\xa2L@\x00\x00\x00\x807\xb6g\xc0\x00\x00\x00\x00\xf8\xe1\x11\xc0\x00\x00\x00\x80B\x02k\xc0\x00\x00\x00\x00\xf0\xa7C@\x00\x00\x00\x80\x05\x1dk\xc0\x00\x00\x00\x00.s+\xc0\x00\x00\x00\xc0\r\x99e@\x00\x00\x00\x00^\x05<@\x00\x00\x00 \xc9\xa1e@\x00\x00\x00\x00j\'3\xc0\x00\x00\x00`\x1e\xafb@\x00\x00\x00\x00\xa2~3@\x00\x00\x00@m\xceb@\x00\x00\x00\x00"3A\xc0\x00\x00\x00\xa0\x93\x92f@\x00\x00\x00\x00\xec\xe8\x18@\x00\x00\x00`~\x89f@\x00\x00\x00\x00"3A\xc0\x00\x00\x00\xa0\x93\x92f@\x00\x00\x00\x00\xec\xe8\x18@\x00\x00\x00`~\x89f@\x00\x00\x00\x00@dD\xc0\x00\x00\x00p\x1e\x99i@\x00\x00\x00\x000!\xf9\xbf\x00\x00\x00`\x1a\xabi@\x00\x00\x00\x00\x1dbL\xc0\x00\x00\x00\x80\xfe\x94q\xc0\x00\x00\x00\x00DU"@\x00\x00\x00\xc0\x04\x1dr\xc0\x00\x00\x00\x00\xca\xffL\xc0\x00\x00\x00@/\\f\xc0\x00\x00\x00\x000\x02;\xc0\x00\x00\x00\xc0\xd9^g\xc0\x00\x00\x00\x80<\x92S\xc0\x00\x00\x00\x00!\x92_\xc0\x00\x00\x00\x80\xdf<Q\xc0\x00\x00\x00\x80\\.a\xc0\x00\x00\x00\x00}eW\xc0\x00\x00\x00\xc0Y\xd1c\xc0\x00\x00\x00\x80\xf9tQ\xc0\x00\x00\x00\x00\xa2ie\xc0\x00\x00\x00\xa0\xfa\xd9f@\x00\x00\x00tS\xdcr@\x00\x00\x00\x00\x86ZA@\x00\x00\x80\xd6\xa8\x8as@\x00\x00\x00 \xa3\x8fa@\x00\x00\x00\x02O\xecr@\x00\x00\x00\x00\\r\x15\xc0\x00\x00\x00\xb6\xbd\x83s@\x00\x00\x00\xc0\r\x0c]@\x00\x00\x008\xd5\xc1r@\x00\x00\x00\x00\xe4m<\xc0\x00\x00\x00\x97YIs@\x00\x00\x00@4\x7fU@\x00\x00\x00\xc0s\x85d\xc0\x00\x00\x00@\xc9\xe3Y@\x00\x00\x00\x00\xe7\xd6b\xc0\x00\x00\x00@4\x7fU@\x00\x00\x00\xc0s\x85d\xc0\x00\x00\x00@\xc9\xe3Y@\x00\x00\x00\x00\xe7\xd6b\xc0\x00\x00\x00@i\xbfQ@\x00\x00\x00`\xde\x1ee@\x00\x00\x00\xc0\xe0\x84[@\x00\x00\x00`X\xcce@\x00\x00\x00@\x85\xe3Q@\x00\x00\x00\x00\xa5\xae^@\x00\x00\x00\xe0\xacA\\@\x00\x00\x00@5\xf3_@\x00\x00\x00\x00\x1a!(@\x00\x00\x00@{\xecc@\x00\x00\x00\x80AOL@\x00\x00\x00 8\x1dd@\x00\x00\x00\x008\xb9\x16\xc0\x00\x00\x00p\xfb\x8cn@\x00\x00\x00\x00\xaf\x89<@\x00\x00\x00\xd0\xa0\xb8n@\x00\x00\x00\x00\xc3\x98@\xc0\x00\x00\x00\xc0\x88)c@\x00\x00\x00\x00\xa0\xa1\x10@\x00\x00\x00 \x9d\xf5b@\x00\x00\x00\x80\xd1IT\xc0\x00\x00\x00\xc0\x83!T@\x00\x00\x00\x00\x03\xe6I\xc0\x00\x00\x00\x00\xc2\xd0R@\x00\x00\x00\x80\xd1IT\xc0\x00\x00\x00\xc0\x83!T@\x00\x00\x00\x00\x03\xe6I\xc0\x00\x00\x00\x00\xc2\xd0R@\x00\x00\x00\xc0\xf6\xccZ@\x00\x00\x00\x00\x14dJ@\x00\x00\x00`/\x93_@\x00\x00\x00\x00\x0exN@\x00\x00\x00\x00\x88\x15\x19\xc0\x00\x00\x00\x00y;a@\x00\x00\x00\x00\t\x9c=@\x00\x00\x00\x00\xa4\x1ea@\x00\x00\x00\x00:\t=\xc0\x00\x00\x00\x00\x80\xc7\xf0?\x00\x00\x00\x00(\xf9\x1b\xc0\x00\x00\x00\x00H\xa9\x11\xc0\x00\x00\x00\x00\xfd3N\xc0\x00\x00\x00\x80\x00\x05q\xc0\x00\x00\x00\x00\x08\xce\x02@\x00\x00\x00@\xe5\xafq\xc0\x00\x00\x00\x80\xb4c[@\x00\x00\x00\x8005c\xc0\x00\x00\x00\x00\xe1\x19^@\x00\x00\x00\x00\xb3*a\xc0\x00\x00\x00\x00\xf0\x86(@\x00\x00\x00 \xd6re@\x00\x00\x00\x80\xefUL@\x00\x00\x00 \xde\xb9e@\x00\x00\x00\x00\xd0\xaa\x11\xc0\x00\x00\x00p\xa2\x11k@\x00\x00\x00\x00sf@@\x00\x00\x00P\x1c<k@\x00\x00\x00\x00\xd0\xaa\x11\xc0\x00\x00\x00p\xa2\x11k@\x00\x00\x00\x00sf@@\x00\x00\x00P\x1c<k@\x00\x00\x00\x00u,G\xc0\x00\x00\x00\xc0\xbd4]@\x00\x00\x00\x00\x842,\xc0\x00\x00\x00\x00\xa2\xb0\\@\x00\x00\x00\x00J\nH@\x00\x00\x00\xa0\xbdjb@\x00\x00\x00\x00\x80*V@\x00\x00\x00@g\xdfb@\x00\x00\x00\x00\x02\x8c=@\x00\x00\x00 >Ca@\x00\x00\x00\x00n\x13Q@\x00\x00\x00`\x84\x90a@\x00\x00\x00\x00:\x9a8@\x00\x00\x00@<\xf0Z@\x00\x00\x00\x00l\xecO@\x00\x00\x00\xc0\x9d\xa2[@\x00\x00\x00\x000\x8f5\xc0\x00\x00\x00\xa0\x89\xccd@\x00\x00\x00\x005\xd94@\x00\x00\x00\xe0\xce\xd9d@', 4, 5, 'ordinal not in range(128)')
You may need to pass the encoding= option to numpy.load

**Comment by zyxrrr** [comment]
I use python2.7
@Dhanalakshmi07

**Comment by Dhanalakshmi07** [comment]
How can we convert tat to python 3

**Comment by zyxrrr** [comment]
convert all functions in all files to python3
@Dhanalakshmi07

**Comment by mikucy** [comment]
@Dhanalakshmi07 Add an encoding option like this
```
dense_matches = np.load(os.path.join(image_data_dir, 'dense_matches.npy'), encoding='latin1')
```
